### ISSUE TITLE
Enable Codecov upload without token?

### ISSUE THREAD

**Issue by gdalle** [SciML/ADTypes.jl#100]
At the moment the tests of #99 seem to fail because of the new release of Codecov. I think @tansongchen doesn't have access to the Codecov token secret, but this could be fixed with [tokenless uploads](https://docs.codecov.com/docs/codecov-tokens#uploading-without-a-token). The thing is, according to their docs, this fix needs to happen on an organization level?
@ChrisRackauckas thoughts?

**Comment by ChrisRackauckas** [comment]
@thazhemadam you said you handled that?

**Comment by ChrisRackauckas** [comment]
Codecov is nasty. No one in the org even has admin there, even the owners. They really messed up our account and so we're emailing customer service 😅

**Comment by thazhemadam** [comment]
Tokenless uploads for running codecov from forks have now been enabled and have been verified to be working[^1].

[^1]: https://github.com/SciML/ModelingToolkit.jl/actions/runs/11967316355?pr=3230
