### ISSUE TITLE
Latest releases are not tagged on GitHub

### ISSUE THREAD

**Issue by gdalle** [SciML/ADTypes.jl#22]
The package is at 0.2.6 and GitHub only shows 0.1.1

**Comment by Vaibhavdixit02** [comment]
@ChrisRackauckas it might be because the https://github.com/SciML/ADTypes.jl/blob/main/.github/workflows/TagBot.yml#L14 is not defined? cc:@thazhemadam

**Comment by gdalle** [comment]
I would be very surprised if there wasn't a SciML-wide GitHub token that can be used here instead of creating a repo-specific one.
The other thing is that the token must be given the correct access, ideally on a job-wise basis with the `permissions` setting:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository
