### ISSUE TITLE
Add AutoDiffractor

### ISSUE THREAD

**Issue by gdalle** [SciML/ADTypes.jl#27]
**Is your feature request related to a problem? Please describe.**

[Diffractor.jl](https://github.com/JuliaDiff/Diffractor.jl) is now a usable AD library in forward mode, but it is not part of ADTypes.jl

**Describe the solution you’d like**

A new struct called `AutoDiffractor`.

**Describe alternatives you’ve considered**

We can also base it on ChainRules.jl with `AutoChainRules(DiffractorRuleConfig())`

**Additional context**

@oxinabox what information or parameters would you put in an `AutoDiffractor` struct? Examples:
- `AutoFiniteDiff` has the finite difference scheme
- `AutoForwardDiff` has the number of chunks

**Comment by oxinabox** [comment]
I don't think we need any struct fields right now.
There is some stuff coming that might need type-parameters, but right now it is basically configuration free.
