### ISSUE TITLE
Add Codecov action

### ISSUE THREAD

**Issue by gdalle** [SciML/ADTypes.jl#41]
I discovered in #40 that some lines were never tested, it would be good to have a Codecov workflow to spot that. With such a small package we should always be at 100% coverage

**Comment by ChrisRackauckas** [comment]
@thazhemadam is going to do an overhaul centralization of our CI scripts soon, so this will get handled at that time.

**Comment by gdalle** [comment]
Still it wouldn't cost much to activate it here, since I spotted uncovered lines and am currently doing a rather big overhaul in #40

**Comment by gdalle** [comment]
I can do the yml part myself but I cannot add codecov as a GitHub app to the repo cause I'm not part of SciML

**Comment by ChrisRackauckas** [comment]
All repos already have codecov.

**Comment by gdalle** [comment]
Cool, I'll add the line to the workflow

**Comment by gdalle** [comment]
Can I ask you for a look at #40 if you have some time? It's very minorly breaking but it will be a huge help for getting sparsity to work across backends
