### ISSUE TITLE
Register v1.0

### ISSUE THREAD

**Issue by gdalle** [SciML/ADTypes.jl#46]
I have just finished implementing a barebones version of SparseDiffTools in DifferentiationInterface:

- coloring : https://github.com/gdalle/DifferentiationInterface.jl/blob/gd/adtypes_v1/DifferentiationInterface/src/coloring.jl
- compressed evaluation + decompression : https://github.com/gdalle/DifferentiationInterface.jl/blob/gd/adtypes_v1/DifferentiationInterface/src/sparse.jl#L113-L346

I can confirm that it works locally, and that the current design of ADTypes v1.0 is all we need for that. Therefore, I would like to suggest **registration of ADTypes v1.0** (and SciMLBase v2.34 following https://github.com/SciML/SciMLBase.jl/pull/674), to make testing possible with CI. For some reason, installation fails on the DifferentiationInterface PR https://github.com/gdalle/DifferentiationInterface.jl/pull/194 despite me committing the manifests.

I have asked for feedback on Slack and Zulip and got no negative response, except for a small remark about the package name (which isn't gonna change).
What do you think?

Keep in mind that the most breaking change is probably the Julia v1.10 compat lower bound, which we decided to put in place because 1.10 will be the new LTS.

cc @ChrisRackauckas @Vaibhavdixit02 @avik-pal @adrhill

**Comment by Vaibhavdixit02** [comment]
I will do a release by evening EST unless someone raises any concerns

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by gdalle** [comment]
Awesome, thanks! A SciMLBase release with the new ADTypes compat bound (already on master) seems to be the last missing piece on my end!
