### ISSUE TITLE
Support older Julia versions?

### ISSUE THREAD

**Issue by lassepe** [SciML/ADTypes.jl#47]
The main thing that stops me from adopting this package is that I don't want to force all my users to upgrade Julia 1.10. ~~As I understand it, dropping support for older Julia versions would be considered a breaking change.~~ I see no fundamental reason why this package would require 1.10 --- package extensions could be used in a backward compatible way.

**Comment by gdalle** [comment]
This was discussed in https://github.com/SciML/ADTypes.jl/pull/40#issuecomment-2055319884 and @ChrisRackauckas suggested we drop Julia versions below 1.10. On second thought, if this is a real pain point for users, I guess there is not much harm in adding back support all the way down to 1.6

**Comment by gdalle** [comment]
After some more discussion, older versions will not be supported, not with a v1.10 LTS around the corner

**Comment by lassepe** [comment]
Okay, sounds good! Also good to know that 1.10 will be the new LTS :)
