### ISSUE TITLE
Recent PR broke the API

### ISSUE THREAD

**Issue by gdalle** [SciML/ADTypes.jl#56]
The recent PR #54 by @adrhill, which was merged by @ChrisRackauckas before I had time to review it, makes things disappear from the public API in a breaking way. In Julia, the documentation _is_ the public API, so we cannot edit docstrings quite however we want.

The things that need to be done are:

- Explicitly document "fields" instead of "keyword arguments", because otherwise users of ADTypes.jl (like DifferentiationInterface.jl) have no API-sanctioned way to access the specifics of a backend object
- Same for type parameters like `AutoChainRules{RC}`, which have disappeared in the PR.

Essentially, I'd prefer to revert the entire PR and then add back this precision everywhere:

```
Struct used to select the ... backend for automatic differentiation.
Exported from ADTypes.jl
```

**Comment by adrhill** [comment]
> In Julia, the documentation is the public API, so we cannot edit docstrings quite however we want.

I understand the issue. #54 changed the documentation from "developer docs" to "user docs" and I didn't have this in mind.
However, since ADTypes are user-facing, I would argue that we need both (see #31). So I think a full revert isn't a long-term solution either.

**Comment by gdalle** [comment]
That's why I said we can add back the user precision
