### ISSUE TITLE
Add a function acyclic_coloring

### ISSUE THREAD

**Issue by amontoison** [SciML/ADTypes.jl#69]
I suggest to add a function for acyclic coloring, which is relerant for Hessian coloring.

cc @gdalle

**Comment by gdalle** [comment]
In the meantime, SparseMatrixColorings has evolved to be a much richer interface than can be provided by ADTypes, so I doubt adding new names here would help much. Closing this for now if that's okay :)

**Comment by amontoison** [comment]
Maybe we can add `bicoloring`?
I think that the variants star / acyclic should a be a kwarg of `symmetric_coloring` and `bicoloring`.
