### ISSUE TITLE
Tapir => Mooncake renaming

### ISSUE THREAD

**Issue by gdalle** [SciML/ADTypes.jl#88]
@willtebbutt @yebai I think we can close #76 and open a new PR that

- adds `AutoMooncake` with the right type parameters and fields (don't get it wrong, as you saw we're not keen on breaking changes around here ^^)
- puts a deprecation warning on `AutoTapir`

What do you say?

**Comment by willtebbutt** [comment]
Yup, will do.

Re correct type parameters and parameter names: would you object to us parametrising them flexibly? i.e. doing something like
```julia
struct AutoMooncake{Tconfig<:Mooncake.Config}
    config::Tconfig
end

config = Mooncake.Config(...)
ADTypes.AutoMooncake(; config)
```
where `Mooncake.Config` is a general configuration handling thing that we may change when we release breaking versions of Mooncake. This way we have some flexibility, while not risking requiring breaking changes to the ADTypes interface.

**Comment by gdalle** [comment]
Sounds good to me

**Comment by gdalle** [comment]
The way things look, the Mooncake renaming in ADTypes and DI will be the last item on the to-do list before the breaking release of DI. Do ping me if I can help in any way!
Btw, the new docs of Mooncake are really cool
