### ISSUE TITLE
Document type-stable constructors

### ISSUE THREAD

**Issue by gdalle** [SciML/ADTypes.jl#96]
Right now, only the constructors with keyword arguments are part of the public API for ADTypes.
This is problematic because e.g. `AutoForwardDiff(; chunksize, tag)` is type-unstable while `AutoForwardDiff{chunksize,typeof(tag)}(tag)` is not.
As a result, DI (and probably other packages too) are forced to use undocumented internal API that may break without notice whenever they want to construct backends efficiently. I suggest we document type-stable variants of every constructor when possible, even if it means adding fallbacks when the number of type parameters increases. For instance, if someday there is an `AutoForwardDiff{chunksize,T,whatever}`, then `AutoForwardDiff{chunksize,T}(tag)` should still work.

Related:

- #94

**Comment by ChrisRackauckas** [comment]
Is this still an issue though? My understanding is that the effect system should be able to optimize out the literals these days? CC @oscardssmith

**Comment by gdalle** [comment]
Doesn't look that way: the keyword version seems to be type-unstable, at least on Julia 1.11.

```julia
julia> struct MyType{A} end

julia> MyType(; A) = MyType{A}();

julia> @code_warntype MyType(; A=1)
MethodInstance for Core.kwcall(::@NamedTuple{A::Int64}, ::Type{MyType})
  from kwcall(::NamedTuple, ::Type{MyType}) @ Main REPL[2]:1
Arguments
  _::Core.Const(Core.kwcall)
  @_2::@NamedTuple{A::Int64}
  @_3::Type{MyType}
Locals
  @_4::Int64
  A::Int64
Body::MyType
1 ─       Core.NewvarNode(:(@_4))
│   %2  = Core.isdefined(@_2, :A)::Core.Const(true)
└──       goto #3 if not %2
2 ─       (@_4 = Core.getfield(@_2, :A))
└──       goto #4
3 ─       Core.Const(:(Core.UndefKeywordError(:A)))
└──       Core.Const(:(@_4 = Core.throw(%6)))
4 ┄ %8  = @_4::Int64
│         (A = %8)
│   %10 = Base.keys(@_2)::Core.Const((:A,))
│   %11 = (:A,)::Core.Const((:A,))
│   %12 = Base.diff_names(%10, %11)::Core.Const(())
│   %13 = Base.isempty(%12)::Core.Const(true)
└──       goto #6 if not %13
5 ─       goto #7
6 ─       Core.Const(:(Base.kwerr(@_2, @_3)))
7 ┄ %17 = Main.:(var"#MyType#3")::Core.Const(Main.var"#MyType#3")
│   %18 = A::Int64
│   %19 = (%17)(%18, @_3)::MyType
└──       return %19
```

**Comment by ChrisRackauckas** [comment]
```julia
using Test
struct MyType{A} end
MyType(; A) = MyType{A}()
function testf()
	MyType(; A=1)
end
@code_warntype optimize=true testf()
```

```
MethodInstance for testf()
  from testf() @ Main ~/Desktop/test.jl:128
Arguments
  #self#::Core.Const(testf)
Body::MyType{1}
1 ─     return $(QuoteNode(MyType{1}()))
```

Global scope.

**Comment by gdalle** [comment]
I don't think so, let's close. I'll switch in DI to use the keyword argument constructors, because I know now that there is no type inference penalty
